repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    exclude: 'tests/testdata/.*yaml$'
  - id: end-of-file-fixer
  - id: check-yaml
    args:
    - --unsafe  # Allow !include and other constructors
  - id: check-added-large-files
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.3.4
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
    - id: codespell
      exclude: |
          (?x)^(
              hostdb/resources/wordlist
          )$
