[tool.mypy]
exclude = [
  "venv/",
  "examples/",
]
platform = "linux"
show_error_codes = true
follow_imports = "normal"
local_partial_types = true
strict_equality = true
no_implicit_optional = true
warn_incomplete_stub = true
warn_redundant_casts = true
warn_unused_configs = true
disable_error_code = [
    "import-untyped",
    # TODO: Fix lint errors and enable these checks
    "attr-defined",
    "return",
    "misc",
    "comparison-overlap",
    "arg-type",
    "return-value",
    "union-attr",
    "valid-type",
    "var-annotated",
]
extra_checks = false
check_untyped_defs = false
disallow_subclassing_any = true
disallow_untyped_decorators = true
warn_unreachable = true
# TODO: Fix lint errors and enable these checks
warn_unused_ignores = false
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
warn_return_any = false
